consumes:
  - application/json
info:
  description: Приложение для МЧС
  title: mchs
  version: 1.0.0
schemes:
  - http
paths:
  /events:
    post:
      operationId: createEvent
      parameters:
        - name: body
          in: body
          schema:
            properties:
              name:
                type: string
              timeStart:
                type: string
              timeFinish:
                  type: string
      responses:
        200:
          description: OK
          schema:
            type: string
        400:
          description: BadRequest
        404:
          description: NotFound
        500:
          description: UnknownError
  /login:
    post:
      operationId: login
      parameters:
        - name: body
          in: body
          schema:
            properties:
              name:
                type: string
              password:
                type: string
      responses:
        200:
          description: OK
          schema:
            type: string
        404:
          description: Неправильные пароль или юзер
        500:
          description: Ошибка сервера
  /users:
    get:
      operationId: listUsers
      parameters:
        - name: session
          in: header
          type: string
        - name: count
          in: query
          type: integer
          format: uint32
          default: 100
        - name: skip
          in: query
          type: integer
          format: uint64
          default: 0
      responses:
        200:
          description: вввв
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                  format: uint64
                name:
                  type: string
        400:
          description: плохой запрос
        500:
          description: unknown error
    post:
      operationId: createUser
      parameters:
        - name: session
          in: header
          type: string
        - name: data
          in: body
          schema:
            $ref: "#/definitions/userDesc"
      responses:
        200:
          description: пользователь создан
          schema:
            type: integer
            format: uint64
        400:
          description: плохой запрос
        404:
          description: плохой запрос
        500:
          description: неизвестная ошибка
  /users  /{id}:
    get:
      operationId: getUser
      parameters:
        - name: id
          in: path
          type: string
          required: true
      responses:
        200:
          description: dddd
    post:
      operationId: updateUser
      parameters:
        - name: id
          in: path
          type: string
          required: true
        - name: body
          in: body
          schema:
            $ref: "#/definitions/userDesc"
      responses:
        200:
          description: dddd
definitions:
  userDesc:
    properties:
      name:
        type: string
        maxLength: 255
      password:
        type: string
        maxLength: 255
    required: [ name, password ]
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
produces:
  - application/json
swagger: "2.0"